<?php

return [
    'title'               => 'កែប្រែកម្មករ',
    'profile_photo'       => 'រូបថតផ្ទៃមុខ',
    'photo_hint'          => 'ចុចលើរូបភាពដើម្បីផ្លាស់ប្តូររូបថត',
    'name'                => 'ឈ្មោះ',
    'username'            => 'ឈ្មោះអ្នកប្រើ',
    'email'               => 'អ៊ីមែល',
    'phone_number'        => 'លេខទូរស័ព្ទ',
    'department'          => 'នាយកដ្ឋាន',
    'gender'              => 'ភេទ',
    'male'                => 'ប្រុស',
    'female'              => 'ស្រី',
    'status'              => 'ស្ថានភាព',
    'active'              => 'សកម្ម',
    'inactive'            => 'មិនសកម្ម',
    'password'            => 'ពាក្យសម្ងាត់',
    'update_worker'       => 'ធ្វើបច្ចុប្បន្នភាពកម្មករ',
    'back'                => '← ត្រលប់ក្រោយ',

    // Validation & error messages
    'photo_error'         => 'ឯកសារត្រូវតែជារូបភាព។',
    'photo_mimes'         => 'រូបភាពត្រូវតែជាប្រភេទ jpeg, png, jpg, ឬ gif ។',
    'photo_max'           => 'ទំហំរូបភាពមិនអាចលើសពី 2MB ។',
    'name_required'       => 'ឈ្មោះជាសារពើភ័ណ្ឌ។',
    'username_required'   => 'ឈ្មោះអ្នកប្រើជាសារពើភ័ណ្ឌ។',
    'username_unique'     => 'ឈ្មោះអ្នកប្រើនេះត្រូវបានប្រើរួចហើយ។',
    'email_required'      => 'អ៊ីមែលជាសារពើភ័ណ្ឌ។',
    'email_unique'        => 'អ៊ីមែលនេះត្រូវបានប្រើរួចហើយ។',
    'password_required'   => 'ពាក្យសម្ងាត់ជាសារពើភ័ណ្ឌ។',
    'password_min'        => 'ពាក្យសម្ងាត់ត្រូវតែយ៉ាងហោចណាស់ 6 តួអក្សរ។',
    'phone_required'      => 'លេខទូរស័ព្ទជាសារពើភ័ណ្ឌ។',
    'gender_in'           => 'សូមជ្រើសរើសភេទដែលមានសុពលភាព។',
];
