<?php

return [
    'title' => 'ワーカーを追加',
    'profile_photo' => 'プロフィール写真',
    'photo_hint' => '画像をクリックして変更',
    'name' => '氏名',
    'username' => 'ユーザー名',
    'email' => 'メールアドレス',
    'phone_number' => '電話番号',
    'department' => '部署',
    'gender' => '性別',
    'male' => '男性',
    'female' => '女性',
    'status' => 'ステータス',
    'active' => 'アクティブ',
    'inactive' => '非アクティブ',
    'password' => 'パスワード',
    'add_worker' => 'ワーカーを追加',
    'back' => '← 戻る',
    'name_placeholder' => 'フルネームを入力してください',
    'username_placeholder' => 'ユーザー名を入力してください',
    'email_placeholder' => '有効なメールアドレスを入力してください',
    'phone_placeholder' => '有効な電話番号を入力してください',
    'department_placeholder' => '部署名を入力してください',
    'password_placeholder' => 'パスワードを入力してください',
    'photo_error' => 'ファイルは画像である必要があります。',
    'photo_mimes' => '画像の形式は jpeg、png、jpg、gif のいずれかでなければなりません。',
    'photo_max' => '画像サイズは2MB以下にしてください。',
    'name_required' => '氏名は必須です。',
    'username_required' => 'ユーザー名は必須です。',
    'username_unique' => 'このユーザー名はすでに使用されています。',
    'email_required' => 'メールアドレスは必須です。',
    'email_unique' => 'このメールアドレスはすでに使用されています。',
    'password_required' => 'パスワードは必須です。',
    'password_min' => 'パスワードは6文字以上で入力してください。',
    'phone_required' => '電話番号は必須です。',
    'gender_in' => '有効な性別を選択してください。',
];
